#!/bin/bash

fancy_echo() {
  printf "\n%b\n" "$1"
}

fancy_echo "Updating system packages ..."
  sudo apt-get update

fancy_echo "Installing git, for source control management ..."
  sudo apt-get install -y git

fancy_echo "Installing curl ..."
  sudo apt-get install -y curl

fancy_echo "Installing OpenJDK ..."
  sudo apt-get install -y openjdk-7-jdk openjdk-7-jre

fancy_echo "Installing Netbeans ..."
  wget http://dlc-cdn.sun.com/netbeans/8.0.2/final/bundles/netbeans-8.0.2-php-linux.sh -O /tmp/netbeans-8.0.2-php-linux.sh
  sudo chmod +x /tmp/netbeans-8.0.2-php-linux.sh
  sudo bash /tmp/netbeans-8.0.2-php-linux.sh --silent
  sudo rm -rf /tmp/*

fancy_echo "Installing Apache, Php, MySQL and required packages installation ..."
  sudo apt-get -y install apache2 php5 libapache2-mod-php5 php5-mcrypt php5-curl php5-mysql php5-gd php5-cli php5-dev mysql-client
php5enmod mcrypt

fancy_echo "Installing Workbench ..."
#TODO precisa testar
  sudo apt-get install -y mysql-workbench-community
  sudo apt-get install -y libmysqlclient18

fancy_echo "Installing Smartgit ..."
  sudo apt-get install -y
  #TODO clonar repositorios vindo de um arquivo de configuração
  
fancy_echo "Updating installed system packages ..."
  sudo apt-get update

fancy_echo "Cleaning Installation ..."
  sudo apt-get autoclean
  sudo apt-get clean
  sudo apt-get autoremove
