#!/bin/bash

fancy_echo() {
  printf "\n%b\n" "$1"
}

fancy_echo "Updating system packages ..."
  sudo apt-get update

fancy_echo "Installing git, for source control management ..."
  sudo apt-get install -y git

#fancy_echo "Installing libraries for common dependencies ..."
#  sudo apt-get install -y 

fancy_echo "Installing OpenJDK ..."
  sudo apt-get install -y openjdk-7-jdk openjdk-7-jre

fancy_echo "Installing Netbeans ..."
  wget http://dlc-cdn.sun.com/netbeans/8.0.2/final/bundles/netbeans-8.0.2-php-linux.sh -O /tmp/netbeans-8.0.2-php-linux.sh
  sudo chmod +x /tmp/netbeans-8.0.2-php-linux.sh
  sudo bash /tmp/netbeans-8.0.2-php-linux.sh --silent
  sudo rm -rf /tmp/*

fancy_echo "Installing curl ..."
  sudo apt-get install -y curl

fancy_echo "Installing VirtualBox ..."
  sudo apt-get install -y

fancy_echo "Installing Vagrant ..."
  sudo apt-get install -y 

fancy_echo "Cleaning Installation ..."
  sudo apt-get autoclean
  sudo apt-get clean
  sudo apt-get autoremove